[project]
name = "nameswapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.8.2.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.12.0",
    "ruff>=0.11.1",
]
