name: Release
on:
  release:
    types: [ published ]

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        python-version: [ "3.13" ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "${{ matrix.python-version }}"
          requirements: 'pyproject.toml'
          upload_exe_with_name: 'NameSwapper'
          options: --onefile, --windowed, --name "NameSwapper"

