name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pyinstaller-build:
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        python-version: [ "3.13" ]
        os: [ ubuntu, macos, windows ]

    runs-on: "${{ matrix.os }}-latest"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: "true"
          cache-suffix: "${{ matrix.python-version }}"
          cache-dependency-glob: 'uv.lock'

      - name: Install Dependencies
        run: uv sync --python "${{ matrix.python-version }}" --dev

      - name: Create Executable
        run: |
          uv run pyinstaller --onefile --windowed --name "NameSwapper-${{ matrix.os }}" --noconfirm src/nameswapper/main.py

      - name: Add to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/*"
          token: '${{ github.token }}'

